version: '3.9'

services:
  postgres-dev:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=bee_there
      - POSTGRES_DB=bee_there_db

  postgres-test:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=bee_there
      - POSTGRES_DB=bee_there_db
