require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'bin/bundle'

Style/Documentation:
  Enabled: false
